CONFIG_MCUX_COMPONENT_driver.lpi2c=y
CONFIG_MCUX_COMPONENT_driver.p3t1755=y
CONFIG_MCUX_COMPONENT_driver.rtc=y
CONFIG_MCUX_COMPONENT_component.eeprom_emulation=y
CONFIG_MCUX_COMPONENT_driver.flash_k4=y
